### ISSUE TITLE
您好，您忘记上传按钮的3d模型了

### ISSUE THREAD

**Issue by ShigemoriHakura** [Forairaaaaa/Chappie-Core#1]
![0TS$J@K0`Q_W$@_3X798$Q7](https://user-images.githubusercontent.com/62388797/185786267-f901870a-bbea-4f66-8d87-89e375af6dad.png)
![64W~9D)Q%$2{M~A1LFWOR`C](https://user-images.githubusercontent.com/62388797/185786270-7c5bab9d-7c18-4516-b4c1-2f2d92f27d80.png)

如图所示

**Comment by Forairaaaaa** [comment]
加进去了
