### ISSUE TITLE
插上电脑，识别COM但不能正常工作

### ISSUE THREAD

**Issue by Yeely0162** [Forairaaaaa/Chappie-Core#7]
当设备插入电脑，就响了一下设备接入声音，过了一会电脑疯狂提示设备断开的声音，检查了好几次硬件是正确焊接的，AXP173也有3V输出给芯片

**Comment by LebinLiang** [comment]
> 

你好！我也在复刻这个项目，想问一下你现在成功了吗？我这边串口能连接上并且打印出来了信息，但是显示屏没有亮起来

**Comment by CodeMan-P** [comment]
1.不出串口，给EN脚高电平出串口，貌似给一次就好了。
2.串口不停断开，按着IO0按键重新上电，进入下载模式，就不重复断开了

**Comment by Forairaaaaa** [comment]
可能是开发板型号问题，换个型号烧录空程序试试
